import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/effects/SmoothScroll";
import LayoutProvider from "./components/common/LayoutProvider";
import Providers from "./components/user/Providers";
import { poppin } from "./constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wission Axis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppin.className}`}>
        <Providers>        
          <SmoothScroll>
          <LayoutProvider>
            {children}
          </LayoutProvider>
        </SmoothScroll>
        </Providers>
      </body>
    </html>
  );
}
